### ISSUE TITLE
1.5.6 compilation issue on ARM based Mac

### ISSUE THREAD

**Issue by mscrivo** [SpringMT/zstd-ruby#74]
After updating to 1.5.6, I am unable to compile the gem's native extension. 

Error:

```
streaming_compress.c:54:5: error: incompatible function pointer types initializing 'RUBY_DATA_FUNC' (aka 'void (*)(void *)') with an expression of type 'size_t (void *)' (aka 'unsigned long (void *)')
[-Wincompatible-function-pointer-types]
    streaming_compress_compact,
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning and 1 error generated.
make: *** [streaming_compress.o] Error 1

make failed, exit code 2
```

System details:
Macbook M1
macOS 14.4.1
Xcode 15.3

**Comment by SpringMT** [comment]
What version of Ruby are you using?

**Comment by mscrivo** [comment]
Ah totally forget that important bit of info 🤦🏼 

`ruby 3.3.0 (2023-12-25 revision 5124f9ac75) [arm64-darwin23]`

compiled with the following args:
`--with-openssl-dir=/opt/homebrew/opt/openssl@3 --with-jemalloc-dir=/opt/homebrew/opt/jemalloc --enable-yjit`

**Comment by mscrivo** [comment]
Actually, I have one more config setting that is relevant:

```
export DLDFLAGS="${DLDFLAGS:-} -Wl,-undefined,dynamic_lookup"
```
and it seems that's the culprit. After removing that, I am able to build the extension. We had to add that to get some other gems's extensions compiling, but perhaps it's no longer required and I can remove it.

**Comment by SpringMT** [comment]
I'm noting the similar issue https://github.com/grpc/grpc/issues/35148.

**Comment by mscrivo** [comment]
yeah actually I spoke too soon, it's still failing to compile even with those flags removed.

**Comment by mscrivo** [comment]
strange thing is I still get the error if I try: `bundle config set build.zstd-ruby --with-cflags=-Wno-error=incompatible-function-pointer-types`

**Comment by SpringMT** [comment]
https://github.com/SpringMT/zstd-ruby/pull/75 should be able to fix it.

**Comment by SpringMT** [comment]
@mscrivo I released 1.5.6.1 https://rubygems.org/gems/zstd-ruby/versions/1.5.6.1.
Please test it!

**Comment by mscrivo** [comment]
it works! thanks again!
